### ISSUE TITLE
有考虑做星铁的面板图么

### ISSUE THREAD

**Issue by qsmmhn** [lc-hongdou/gallery#2]

**Comment by lc-hongdou** [comment]
现在没那个环境了，我做这个的时候QQ群很多人都在扣图，而且有很多好看的图扣，现在QQ群解散了，另外我崩铁退坑了，不会扣可以联系我帮扣一扣，做图包就算啦，不过本身做图包不难，感兴趣可以教你

**Comment by lc-hongdou** [comment]
崩铁的面板图其他人也有做，不过很少更新了https://gitee.com/yuan_hu_sheng/StarRail-plugin-PanelPic
